[nodelink]
APPOVHNOD2          ansible_host=10.10.100.12
SRVGRCNOD01         ansible_host=10.10.100.13
PXYZABOVHNOD02      ansible_host=10.10.100.14
N8NOVHNOD1_DMZ      ansible_host=10.150.0.2
RPROXYOVHNOD01      ansible_host=10.150.3.4
PXYZABOVHNOD01      ansible_host=10.150.4.1

[alpol]
ZABFRALP1           ansible_host=172.18.35.150

[linux:children]
nodelink
alpol