[nodelink]
APPOVHNOD2          ansible_host=10.10.100.12
NETBOXOVHNOD01      ansible_host=10.10.100.15

[alpol]
ZABFRALP1           ansible_host=172.18.35.150

[stella]
ZABBEMOU1           ansible_host=172.21.31.160

[linux:children]
nodelink
alpol
stella